### ISSUE TITLE
Publish to PowerShell Gallery

### ISSUE THREAD

**Issue by dermeister0** [cdhunt/PowerVault#1]
I noticed that the module is not updated for 2 years, but it works fine. Please publish it to https://www.powershellgallery.com/ repository.

**Comment by cdhunt** [comment]
It has been published. 

https://www.powershellgallery.com/packages/PowerVault/1.0

The tests don't work because for some reason IWR can't pull down the file from Hashicorp's server anymore. That's kind of annoying, but I'll take your word for it that it still works.
